// Package config loads kram-gateway's YAML configuration: which upstream
// providers exist, how they're grouped into fallback combos, and which
// routing strategy each combo uses.
package config

import (
	"fmt"
	"os"

	"github.com/codexmark/kram/internal/localstore"

	"gopkg.in/yaml.v3"
)

// generatedHeader is prepended to every file Save writes — yaml.Marshal
// has no comment-preservation story, so this is a plain string banner
// rather than an attempt to annotate individual fields.
const generatedHeader = "# Generated by Kram first-run setup — run \"kram --setup\" to reconfigure.\n" +
	"# Advanced routing (weights, gates) can be tuned here — see DECISIONS.md.\n"

// ProviderConfig describes one upstream LLM backend.
type ProviderConfig struct {
	ID string `yaml:"id"`
	// Kind selects the adapter: "anthropic", "gemini", "openai-compat", or
	// "openai-responses" (the ChatGPT-login-only Codex backend — see
	// internal/provider/openai_responses.go).
	Kind string `yaml:"kind"`
	// BaseURL is the upstream API root. Optional for kinds with a
	// well-known default (anthropic, gemini, openai-responses).
	BaseURL string `yaml:"base_url,omitempty"`
	// APIKeyEnv names the environment variable holding the credential —
	// for AuthMode "oauth" it's used purely as the lookup key into the
	// credentials store's OAuth token map, not as a real env var.
	APIKeyEnv string `yaml:"api_key_env"`
	// AuthMode selects how the gateway resolves this provider's
	// credential. Empty (the default) is today's behavior: read
	// APIKeyEnv from the process environment once at startup and use it
	// for the provider's lifetime. "oauth" means the credential is a
	// refreshable token in internal/credentials' OAuth store, resolved
	// live on every request (see internal/gateway.Run) since it can
	// expire mid-session — see internal/credentials.Store.Resolve.
	AuthMode string `yaml:"auth_mode,omitempty"`
	// KeyOptional means APIKey should return an empty string instead of an
	// error when APIKeyEnv isn't set — true only for
	// internal/customprovider entries, most of which point at a local/LAN
	// server with no auth at all. Every other provider keeps the strict
	// default: an unset env var is a real misconfiguration worth failing
	// loudly on (a clear startup error beats a confusing 401 later).
	KeyOptional bool `yaml:"key_optional,omitempty"`
	// Model is the upstream model ID to request, if it should be pinned
	// regardless of what the client asked for. Empty means passthrough.
	Model string `yaml:"model,omitempty"`
	// Temperature pins a fixed sampling temperature for this provider,
	// overriding whatever the client's request carries (today, that's
	// always nothing — openai.ChatCompletionRequest.Temperature exists on
	// the wire type but nothing in Kram ever populates it, so every
	// request defers entirely to the upstream server's own default
	// unless this is set). A pointer so "never set" (the common case) is
	// distinguishable from "explicitly pinned to 0.0" — a real,
	// maximally-deterministic value someone might genuinely want, not
	// the same as leaving it alone. Currently only honored by the
	// openai-compat adapter (internal/provider/openai_compat.go) — see
	// its own doc comment for why the other three kinds aren't wired up
	// yet.
	Temperature *float64 `yaml:"temperature,omitempty"`
	// SupportsImages declares whether this provider's model accepts image
	// input. Callers must check this (via /admin/status) before attaching
	// images — the gateway never guesses.
	SupportsImages bool `yaml:"supports_images,omitempty"`
	// SupportsTools declares whether this provider's model can be sent
	// tool/function definitions. Kram's agent loop skips providers that
	// don't when a request requires tool calling.
	SupportsTools bool `yaml:"supports_tools,omitempty"`
	// QualityHint is an optional, explicitly user-configured 0..1 signal
	// feeding the "quality" scoring factor (see internal/router) —
	// deliberately never inferred or fabricated by Kram itself, since
	// there is no real per-provider quality measurement to derive it
	// from. Zero means "no opinion", which the scorer treats as neutral
	// (0.5), not "worst possible" — see DECISIONS.md.
	QualityHint float64 `yaml:"quality_hint,omitempty"`
}

// APIKey resolves the provider's credential from its configured env var.
func (p ProviderConfig) APIKey() (string, error) {
	if p.APIKeyEnv == "" {
		return "", nil
	}
	v := os.Getenv(p.APIKeyEnv)
	if v == "" && !p.KeyOptional {
		return "", fmt.Errorf("provider %q: env var %s is not set", p.ID, p.APIKeyEnv)
	}
	return v, nil
}

// StrategyOptions tunes a combo's routing strategy — every field is
// optional, and an absent strategy_options block (the whole existing v0
// config shape) means "use the strategy's own defaults", never a required
// section. Pointers distinguish "not set, use the default" from "set to
// the zero value", which matters for Sticky in particular (explicitly
// disabling stickiness is a real, different choice from never mentioning
// it).
type StrategyOptions struct {
	// Sticky pins a run (see router.RunKey) to its winning provider
	// across tool round-trips, only used by the weighted (smart/quality/
	// fast/cheap/reliable/custom) strategy family. Defaults to true for
	// that family if unset — see DECISIONS.md, "Sticky by default".
	Sticky *bool `yaml:"sticky,omitempty"`
	// LKGPBoost is the additive score bonus (0..1) a candidate gets when
	// it's the combo's current last-known-good provider, on top of its
	// own weighted score. 0 (the zero value) if unset would disable the
	// boost entirely, so an unset field falls back to a small nonzero
	// default instead — see router.defaultLKGPBoost.
	LKGPBoost *float64 `yaml:"lkgp_boost,omitempty"`
	// Exploration is the probability (0..1) of picking a uniformly random
	// eligible candidate as the leader instead of the top-ranked one, so
	// non-winning candidates still occasionally get real telemetry — see
	// DECISIONS.md, "Exploration". Small and conservative by default.
	Exploration *float64 `yaml:"exploration,omitempty"`
	// Weights overrides the weighted strategy's per-factor weights
	// (health, reliability, latency, quality, cache_affinity, priority).
	// Any factor not mentioned keeps its preset's weight; values are
	// normalized automatically, so they don't need to sum to any
	// particular total.
	Weights map[string]float64 `yaml:"weights,omitempty"`
}

// ResponseGateConfig configures deterministic, technical validation of an
// otherwise-successful response before it's allowed to end the fallback
// chain — see router.ResponseGate. Every field is opt-in; an absent
// response block disables gating entirely (the v0 behavior: any
// technically-successful response is accepted).
type ResponseGateConfig struct {
	// RejectEmpty rejects a response with neither text content nor tool
	// calls.
	RejectEmpty bool `yaml:"reject_empty,omitempty"`
	// RequireTerminal rejects a stream that never produced a proper
	// finish signal (e.g. a connection that was cut mid-stream) even if
	// it carried some content.
	RequireTerminal bool `yaml:"require_terminal,omitempty"`
	// MinContentLength rejects a text response shorter than this many
	// characters (tool-call-only responses are exempt — a short "ok,
	// calling the tool now" isn't what this guards against).
	MinContentLength int `yaml:"min_content_length,omitempty"`
	// ForbiddenSubstrings rejects a response whose content contains any
	// of these — for masked upstream errors that come back as HTTP 200
	// with an error message as the body, not for filtering legitimate
	// model output.
	ForbiddenSubstrings []string `yaml:"forbidden_substrings,omitempty"`
}

// ComboConfig is a named, ordered fallback chain of providers plus the
// strategy used to pick among the healthy ones.
type ComboConfig struct {
	ID              string             `yaml:"id"`
	Strategy        string             `yaml:"strategy"` // "round-robin" in v0; see internal/router for the full set
	Providers       []string           `yaml:"providers"`
	StrategyOptions StrategyOptions    `yaml:"strategy_options,omitempty"`
	Response        ResponseGateConfig `yaml:"response,omitempty"`
}

// Config is the top-level gateway configuration.
type Config struct {
	Host      string           `yaml:"host"`
	Port      int              `yaml:"port"`
	Providers []ProviderConfig `yaml:"providers"`
	Combos    []ComboConfig    `yaml:"combos"`
	// DefaultCombo is used when a request's "model" doesn't match a combo ID.
	DefaultCombo string `yaml:"default_combo"`
	// Tunables overrides the operational timeouts and breaker thresholds
	// that were previously compiled-in constants. Optional — an absent
	// block reproduces the old behavior exactly. See tunables.go.
	Tunables Tunables `yaml:"tunables,omitempty"`
}

// Load reads and validates a YAML config file.
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading config %s: %w", path, err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing config %s: %w", path, err)
	}

	if cfg.Host == "" {
		cfg.Host = "127.0.0.1"
	}
	if cfg.Port == 0 {
		cfg.Port = 20128
	}

	if err := cfg.validate(); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// Save writes cfg as YAML to path (with the generated-file banner
// prepended), creating parent directories as needed. The write is atomic
// via localstore.AtomicWrite — a reader, or a crash mid-write, never
// observes a half-written config.
func Save(cfg *Config, path string) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("encoding config: %w", err)
	}
	return localstore.AtomicWrite(path, append([]byte(generatedHeader), data...), 0o644)
}

func (c *Config) validate() error {
	if len(c.Providers) == 0 {
		return fmt.Errorf("config: at least one provider is required")
	}
	ids := make(map[string]bool, len(c.Providers))
	for _, p := range c.Providers {
		if p.ID == "" {
			return fmt.Errorf("config: provider missing id")
		}
		if ids[p.ID] {
			return fmt.Errorf("config: duplicate provider id %q", p.ID)
		}
		ids[p.ID] = true
		switch p.Kind {
		case "anthropic", "gemini", "openai-compat", "openai-responses":
		default:
			return fmt.Errorf("config: provider %q has unknown kind %q", p.ID, p.Kind)
		}
		if p.AuthMode != "" && p.AuthMode != "oauth" {
			return fmt.Errorf("config: provider %q has unknown auth_mode %q", p.ID, p.AuthMode)
		}
	}

	if len(c.Combos) == 0 {
		return fmt.Errorf("config: at least one combo is required")
	}
	comboIDs := make(map[string]bool, len(c.Combos))
	for _, combo := range c.Combos {
		if combo.ID == "" {
			return fmt.Errorf("config: combo missing id")
		}
		if comboIDs[combo.ID] {
			return fmt.Errorf("config: duplicate combo id %q", combo.ID)
		}
		comboIDs[combo.ID] = true
		if len(combo.Providers) == 0 {
			return fmt.Errorf("config: combo %q has no providers", combo.ID)
		}
		for _, pid := range combo.Providers {
			if !ids[pid] {
				return fmt.Errorf("config: combo %q references unknown provider %q", combo.ID, pid)
			}
		}
	}

	if c.DefaultCombo != "" && !comboIDs[c.DefaultCombo] {
		return fmt.Errorf("config: default_combo %q is not a defined combo", c.DefaultCombo)
	}

	// Tunables are optional, but a negative duration or threshold is never
	// meaningful and would silently disable the guard it configures (a
	// negative timeout, once resolved, would compare as "already elapsed").
	// Reject it loudly rather than let it brick the setting.
	if c.Tunables.ProviderTimeout < 0 {
		return fmt.Errorf("config: tunables.provider_timeout must not be negative")
	}
	if c.Tunables.GatewayClientTimeout < 0 {
		return fmt.Errorf("config: tunables.gateway_client_timeout must not be negative")
	}
	if c.Tunables.BreakerCooldown < 0 {
		return fmt.Errorf("config: tunables.breaker_cooldown must not be negative")
	}
	if c.Tunables.BreakerFailureThreshold < 0 {
		return fmt.Errorf("config: tunables.breaker_failure_threshold must not be negative")
	}
	return nil
}
